services:
  eurovision-dashboard:
    build: .
    container_name: eurovision-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./results:/app/results
      - ./data:/app/data

  eurovision-pipeline:
    build: .
    container_name: eurovision-pipeline
    command: ["python", "pipeline.py", "--votes", "100000", "--duration", "30"]
    volumes:
      - ./results:/app/results
      - ./data:/app/data
